import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Header} from "@/components/Header";
import Footer from "@/components/Footer";
import { getGlobalData } from "@/data/loaders";
import Announcement from "@/components/Announcement";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const globalData = await getGlobalData();
  console.dir(globalData, { depth: null });

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Announcement/>
        <Header data={globalData.data.header} /> 
        {children}
        <Footer/> 
      </body>
    </html>
  );
}
